### ISSUE TITLE
Old FFMPEG version, cannot use cuda - GPU accelerated h264 encoding

### ISSUE THREAD

**Issue by balamacab** [mi-g/vdhcoapp#1]
Please update the ffmpeg version to 3.3.3 and allow the use of a custom encoding codec to select the h264_nvenc, to use the GPU to encode the video.

**Comment by mi-g** [comment]
This is what we did originally, but it turned out that ffmpeg >=3 was not capable of joining files audio + video files downloaded from the dash protocol.

**Comment by luziferius** [comment]
For older ffmpeg versions you can use _nvenc_h264_  as a video codec. This is deprecated in newer versions, but should work, if you are forced into an older version.

(Unrelated note: The nvenc h264 encoder gives really bad quality when compared to libx264 at a comparable bitrate, so i would suggest to not using it for long-term storage purposes.)

**Comment by mi-g** [comment]
The problem will be partially resolved for Linux, when #49 will be solved. 
Other than that, we won't have the resource to support users willing to use their GPU from ffmpeg as it requires a lot of tuning.
Closing this issue.
