### ISSUE TITLE
Apple M1 Mac not compatible with current version (1.8.6)

### ISSUE THREAD

**Issue by TS6ix2GaH3q679h5** [mi-g/vdhcoapp#105]
Title says it all. Both Pkg and Dmg are failing for me. Installations can't even begin.

**Comment by cblte** [comment]
Just installed the .pkg file from the website

Output of VDH Settings:

```
Found companion app: VdhCoApp 1.6.3
Companion app binary: /Applications/net.downloadhelper.coapp.app/Contents/MacOS/bin/net.downloadhelper.coapp-mac-64
```

Works for me on multiple platforms.

**Comment by TS6ix2GaH3q679h5** [comment]
> Just installed the .pkg file from the website

Must have got a corrupted download. Yesterday's .pkg still doesn't install, but redownloaded from website today and worked fine. Closing this thread. Thanks for the verification.
