### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by moriel5** [mi-g/vdhcoapp#109]
Hello, I want to package ```vdccoapp``` for Solus, however since I want to follow Solus's best practice guidelines, this means that I am not going to use _/usr/local_, rather relying on the traditional _/usr/bin_ _/usr/lib64_ (if applicable) and _/usr/share_.

How would I go about this in this instance?

**Comment by mi-g** [comment]
I don't know specifically about Solus, but you can create packages for any Linux distros. You can use another installation directory as long as the created manifest files point to the right place. However note that most (all?) linux best practices recommand putting externally installed applications into `/usr/local` or `/opt` . The directory `/usr/bin` are for applications that are natively part of the distro.

**Comment by moriel5** [comment]
Thanks, that should be enough for me to figure it out.

As for ```/usr/local``` and ```/opt```, from what I had learned, those depend on the environment (for example, if they use dependencies independent of the OS, or a local app distribution separate from the rest of the OS), so while it is possible that this may be better for _vdccoapp_ (I'll look into this, and if so, then Solus guidelines mandate it to have it's own directory under /usr/share), from my preliminary view which is limited, it looks as though those might not really be the best option for _vdccoapp_.
