### ISSUE TITLE
deb file for glibc 2.28?

### ISSUE THREAD

**Issue by djl0** [mi-g/vdhcoapp#111]
Apologies if this is the wrong place to put this question. I was trying to download from vimeo and got an error saying it was looking for glibc 2.29. I'm on mx linux and I have 2.28. Am I SOL on this? Does anyone have any recommendations? This is a little bit past my level of linux knowledge, so I don't know if there's something like doing my own vcdcoapp build that might be my solution.

Thanks!

**Comment by mi-g** [comment]
Releases of vdhcoapp contain builds for 3 versions of GLIBC: 2.23, 2.27 and 2.31 (default): [https://github.com/mi-g/vdhcoapp/releases/tag/v1.6.3](https://github.com/mi-g/vdhcoapp/releases/tag/v1.6.3)
If your linux distro runs with GLIBC 2.28, you should use the GLIBC 2.27 version of the coapp.
