### ISSUE TITLE
Why does the same video download once, then suddenly requires the companion app? Sounds scammy AF.

### ISSUE THREAD

**Issue by SlidingHorn** [mi-g/vdhcoapp#113]
Title explains it all. This is super shady.

**Comment by mi-g** [comment]
Since suddenly, 3 years ago, Firefox 55 moved to the Web Extensions API disabling a lot of necessary APIs used by VDH. This subject has been largely covered. Make your searches for the details.

**Comment by SlidingHorn** [comment]
That doesn't answer why I can download a video....reload *that same page* and then try to download *that same video again* and it suddenly requires the companion app.

That's adware-like "SIGN UP & PAY FOR OUR PREMIUM SERVICE!" level stuff.

**Comment by mi-g** [comment]
You are posting to the technical issues section of an open source application. Check the Video DownloadHelper support forum instead. And again, make your searches before as your concerns have already been addressed many times.

**Comment by SlidingHorn** [comment]
> Check the Video DownloadHelper support forum instead

I don't use google products, and it's a google groups forum.
