### ISSUE TITLE
FFMPEG License/Code

### ISSUE THREAD

**Issue by rober42539** [mi-g/vdhcoapp#119]
Just curious, are you providing a copy of the source and any modifications you have made to FFMPEG for the Companion App? You're FFMPEG you ship with the Companion App doesn't seem to provide the modified source or instructions to obtain the modified source.

**Comment by mi-g** [comment]
The vdhcoapp project, being under GPL license, provides all its source code in the public github repository.
FFMPEG and a bunch of associated libraries are used unmodified and are invoked through an exec call.
The file BUILD.md contains the instructions on how to obtain the source code of FFMPEG (and libs) in the exact version that were used when building the binary released on github, basically, using the script `converter/get-source.sh`.
