### ISSUE TITLE
failed aggregating - error loading libnuma.so.1

### ISSUE THREAD

**Issue by step-** [mi-g/vdhcoapp#12]
I installed net.downloadhelper.coapp-1.1.0-1_amd64.tar.gz. coapp's ffmpeg fails with the message below. NUMA isn't available for my Linux/GNU box. Is libnuma a strict requirement for coapp to work? Thanks.
```
Failed aggregating ...

/usr/local/net.downloadhelper.coapp-1.1.0/converter/build/linux/64/ffmpeg: error while loading shared libraries: libnuma.so.1: cannot open shared object file: No such file or directory
```

**Comment by mi-g** [comment]
Apparently libnuma is to be used as a dependency of the coapp or one of the libs.
Some users reported it worked after installing libnuma on the system.
If you use Fedora, maybe from there: [https://www.rpmfind.net/linux/rpm2html/search.php?query=libnuma.so.1()(64bit)](https://www.rpmfind.net/linux/rpm2html/search.php?query=libnuma.so.1()(64bit)) ?

**Comment by step-** [comment]
Yes, libnuma is one of the dependencies. I compiled in installed it and now coapp works. But it's a rather unusual dependency, given that NUMA is a distributed memory system - high-end hardware stuff as I understand. My thinking is that either coapp or ffmpeg require libnuma. If it's ffmpeg, and it's a compile option, I suggest to turn it off and recompile ffmpeg. If it's coapp requiring libnuma, then what for? Thanks.

**Comment by mi-g** [comment]
I'm pretty sure it's not the coapp itself. It's either ffmpeg or one of the libraries that go with it.
Since it's open-source and totally free on Linux, i hope someone will take the time to fix it before this issue comes at the top of the priority list. A better solution than to remove the libnuma requirement (which might not be possible anyway), is to compile it as part of the package, like this is the case for libz.

**Comment by step-** [comment]
Exactly from which binary package did you extract the ffmpeg that's included in https://github.com/mi-g/vdhcoapp/releases/download/v1.1.1/net.downloadhelper.coapp-1.1.1-1_amd64.tar.gz?

**Comment by mi-g** [comment]
The ffmpeg programs (ffmpeg, ffprobe and ffplay) are not extracted from a binary package but compiled from scratch, along with a bunch of libraries. Look at [the converter sub-directory](https://github.com/mi-g/vdhcoapp/tree/master/converter), there are 2 scripts:
- `get-source.sh`: connect to various servers and get source code
- `build-apps.sh`: compile everything (on Linux, compile for Linux and Windows, on Mac, compile for Mac)

**Comment by zioalex** [comment]
I have the same problem. The file suggested to download net.downloadhelper.coapp-1.1.3-1_amd64.tar.gz doesn't contain any compiler option. It has only the binaries.

I workaround pointing to the OS ffmpeg* executables:
```cd converter/build/linux/64/
mv ffmpeg ffmpeg.netdl
mv ffplay ffplay.netdl
mv ffprobe ffprobe.netdl
ln -s /usr/bin/ffmpeg ; ln -s /usr/bin/ffplay ; ln -s /usr/bin/ffprobe 
```
But that dependency should be pulled in or removed.

**Comment by mi-g** [comment]
[vdhcoapp 1.2.1](https://github.com/mi-g/vdhcoapp/releases/tag/v1.2.1) includes its own build of library libnuma in case it is not available by default on the target linux distribution.
