### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by bundy4670** [mi-g/vdhcoapp#120]
hi team
https://www.downloadhelper.net/update?browser=firefox&from=7.3.8a1&to=7.6.3a1
since updating of both firefox and then the application net.downloadhelper.coapp
checking it and running the extension on FireFox I get the following error

Checking companion app returned: No such native application net.downloadhelper.coapp

any ideas?
cheers

**Comment by mi-g** [comment]
Unless it is an issue that is clearly related to the companion app, support for VDH is done from the dedicated forum: https://groups.google.com/g/video-downloadhelper-q-and-a/c/
Thanks.

**Comment by dmadsen** [comment]
The url you supplied gets a 404.  Are you sure it's correct?

Thanks!

**Comment by mi-g** [comment]
Sorry, it's https://groups.google.com/g/video-downloadhelper-q-and-a
