### ISSUE TITLE
Companion app not detected on Firefox 98 on Ubuntu 21.10

### ISSUE THREAD

**Issue by lifeboy** [mi-g/vdhcoapp#124]
The companion app is installed via die 64 bit .deb file, but not detected by the browser.

In about:config the net.downloadhelper.coapp is set to true.

How can I troubleshoot this please?

**Comment by lifeboy** [comment]
After reading https://github.com/mi-g/vdhcoapp/issues/96 I checked and I had Firefox installled via snap.  I have removed it and re-installed via apt and now the coapp works 100%.

Maybe a little note in the readme file to alerts users to this would serve well?

**Comment by mi-g** [comment]
Yes, we'll make a notice about in the next version of the coapp.
