### ISSUE TITLE
[Enhancement] Warning Message if Closing Firefox While Still Downloading with Companion App?

### ISSUE THREAD

**Issue by loxia01** [mi-g/vdhcoapp#129]
When downloading files with companion app in Firefox (as opposed to downloading files via the browser) there is no warning message if you close Firefox while still downloading files. All downloads are lost when Firefox exit.

Is it possible to implement a warning message for companion app in Firefox when trying to close the browser while still downloading?

**Comment by mi-g** [comment]
From memory, i have tried to implemented what you are suggesting a few years ago but realized there was no way to block the closing of the browser. I assume the regular Firefox download manager, that is able to suspend the browser exit, accesses an API that is not open to extensions.
