### ISSUE TITLE
Setup repositories for the Debian/Ubuntu packages

### ISSUE THREAD

**Issue by Johann-Tree** [mi-g/vdhcoapp#13]
Could you setup repositories for the Debian/ Ubuntu install packages, please?
It's very annoying to download and install a new coapp-version so often manually, especially on slow internet connections, before you're able to download the actual file you wanted.

**Comment by mi-g** [comment]
Sorry, this is not the priority for now, but this will certainly happen. Note that coapp updates should happen less and less often while gaining in maturity.

**Comment by Johann-Tree** [comment]
Thanks!

**Comment by mettacrawler** [comment]
Aptly makes it easy to set up a repository:
https://www.aptly.info/

Using a PPA is even easier than that:
https://help.launchpad.net/Packaging/PPA

**Comment by bernayss** [comment]
I am trying to install https://github.com/mi-g/vdhcoapp.git and it is how? How to install?
Why is there no Sudo-Install lines for TERM?
I have no idea how to install any 'SNAPS!"

**Comment by mi-g** [comment]
Generally users willing to install *vdhcoapp* come from [this page](https://www.downloadhelper.net/install-coapp) and they see the install procedure:

*targz user-wide install*
```
# tar xf net.downloadhelper.coapp-1.2.4-1_amd64.tar.gz -C ~
# ~/net.downloadhelper.coapp-1.2.4/bin/net.downloadhelper.coapp-linux-64 install --user
```

*targz system-wide install*
```
# sudo tar xf net.downloadhelper.coapp-1.2.4-1_amd64.tar.gz -C /usr/local
# sudo /usr/local/net.downloadhelper.coapp-1.2.4/bin/net.downloadhelper.coapp-linux-64 install --system
```

**Comment by bernayss** [comment]
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cyfex** [comment]
Is it done yet?
