### ISSUE TITLE
The package is of bad quality

### ISSUE THREAD

**Issue by coiby** [mi-g/vdhcoapp#14]
Hi

Thank you for all the efforts.  When I try to install the deb file, a warning is given by package manager,
>**The package is of bad quality**
> The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

> E: net.downloadhelper.coapp: dir-or-file-in-etc-opt etc/opt/chrome/
> E: net.downloadhelper.coapp: dir-or-file-in-etc-opt etc/opt/chrome/native-messaging-hosts/
> E: net.downloadhelper.coapp: dir-or-file-in-etc-opt etc/opt/chrome/native-messaging-hosts/net.downloadhelper.coapp.json

It seems the package violate [Debian policy](http://www.debian.org/doc/debian-policy/ch-controlfields.html).

**Comment by mi-g** [comment]
It looks like the installer complains about the coapp .deb file writing to  `/etc/opt/chrome`, however we have no choice here: this is where the browser looks for the native application manifest.

**Comment by mi-g** [comment]
Cleaning up bug entries.
