### ISSUE TITLE
[Error] Add-on can't connect to Companion App on Firefox Developer

### ISSUE THREAD

**Issue by ploedman** [mi-g/vdhcoapp#141]
Greetings,

I'm not sure if the last update for the Firefox Developer broke something. I currently run the Version 106.0b3 on Windows.

Today I wanted to download a Video with the Add-on, but got a prompt saying I need to install the Companion App, which I already had.
The Add-on trows an Error: "Checking companion app returned: An unexpected error occurred". 

A week ago there was not a issues. I tested it with the Standard Firefox Version, it did find the Companion App without a problem.
On a side note, the Developer Edition of Firefox is not on the OS System Hard disk installed, which wasn't a issues a while ago.

Already reinstalled the Companion App without any help.

**Comment by mi-g** [comment]
This problem has been identified as a Firefox regression and the fix will be in Firefox 106.0b4: https://bugzilla.mozilla.org/show_bug.cgi?id=1791788
