### ISSUE TITLE
Video title need to use timestamps instead of numbering

### ISSUE THREAD

**Issue by jkemp814** [mi-g/vdhcoapp#144]
Hello everyone,

I have an issue that occurs when I move the downloaded videos to another directory, the companion app will restart the numbering, so when I go to transfer the new videos with the same name there is a conflict. I have to manually rename the title. And I have to search what was the last number used.

If the companion app used timestamps in the title, this wouldn't happen. Even if I restart a failed download seconds later, it would have a different name/title.

ffmpeg uses this string: 'what ever the file name is-$(date +"%H-%M-%m-%d-%y").mp4'

Great app,

James

**Comment by mi-g** [comment]
Sorry, the companion app does not know about video titles and only deals with lower level concerns. You may want to check the extension support forum for this kind of issue. But for that matter, the VDH extension allows downloads with explicit naming and automatic naming (called quick download). In the first case, you choose the name you want and the second one use the Firefox standard: if a xxx.mp4 exists, it creates a xxx-1.mp4 file or xxx-y.mp4 where y increments depending on other files in the folder. I don't think it is a good idea to implement an intermediary naming method that would confuse many users. But thanks for the suggestion.
