### ISSUE TITLE
Failed Aggregating: Can't Load libbz2.so.1.0

### ISSUE THREAD

**Issue by rgheck** [mi-g/vdhcoapp#15]
Error seen on Fedora 26. This particular link does not exist, though libbz2.so and libbz2.so.1 and libbz2.so.1.0.6 all do. Easy enough to fix by creating the symlink, but wonder if there is something else you could do here.... Maybe just load libbz2.so.1?

**Comment by mi-g** [comment]
[vdhcoapp 1.2.1](https://github.com/mi-g/vdhcoapp/releases/tag/v1.2.1) includes its own libbz2 which solves the problem on linux distributions where this library is not installed by default.
