### ISSUE TITLE
User anonymity & safety when using firefox internal VPN proxy for privacy addons

### ISSUE THREAD

**Issue by methuzla** [mi-g/vdhcoapp#18]
### **_VDH+_vdhcoapp_ should  honour the current proxy the user thinks they have in place._**

There are various addons for firefox which provide a degree of user anonymity, and sometimes bypass unfriendly firewalls.
If a user has one of these in effect, it seems that VDH + _vdhcoapp_ steps outside the 'VPN' cloak, exposing the user's real IP _without warning._

This could lead to serious consequences in countries where civil liberties and freedom of expression are poorly respected. 

The _"without warning"_ in itself is a cause for concern and irresponsible where naive users are concerned. 

[downloadhelper.net/install-coapp](url) is a little economical with the truth: 
>  "How safe is it to install and run the companion app ?"
>  "The companion application is very safe …" 
         _(not)_

Unless _vdhcoapp_  uses a proxy different from the current firefox proxy, or bypasses the system-wide proxy, or there isn't a proxy in use, for most users naturally this is not going to be a problem.

As a companion app which accesses the wider net in the background, I feel _vdhcoapp_ bears a responsibility to be 'safe' or at least to warn potentional users if it is _not_ 'safe' with regard to secure privacy. 
Currently it  accesses the net in a way the user might not expect, is not led to expect, which could be regarded as irresponsible.

I suggest that this inadequacy be addressed in some way.

-  One solution would be to have _vdhcoapp_ pick up the current firefox proxy & use that.
-  Another could be for _vdhcoapp_ to ask for a proxy: warn, ask, suggest, default, setting, reminder. 
     This would need much more code.
-  At the very least warnings about proxy access _'should'_ be prominently documented, with suitable warnings about leaky config settings (consider https://ipleak.net/ )

As for Firefox itself, management is and has for some time been in abrogation of its stated mission in imposing various defaults which leak users' identities, often in vicarious pursuit of fashion. One can only hope the current bunch of souls in charge will move on as soon as practicable, before firefox ceases to be relevant (there _is_ good work going on, too).
There are Firefox config entries that can be altered _if_ the user is warned about them (peerconnction etc,) as some privacy addons do warn but many don't.  
VDH with _vdhcoapp_ would begin to fall into this bracket of needing good policy to inform the user.

The above may apply to other browsers too.

Blessings.

**Comment by mi-g** [comment]
This is currently in Video DownloadHelper 7.1.2aX development. Downloads are now re-using the same proxy as the initial browser request. It will go mainstream (7.1.2) in the next couple of days.

**Comment by methuzla** [comment]
### Hi, @mi-g 

### _Many thanks for sorting it out!_

I mentioned this a long time ago in the main forum, but it seemed to have been buried and forgotten, so I thought I'd waken it up here. Apologies, I was unaware of the dev stream - is that published anywhere?

Will you be asking the tech writer bods to update the ff AMO & webpage [downloadhelper.net/install-coapp](url) as well? (Or, are you the tech writer bod as well?)

Will this be the same for rival browsers?

**Comment by mi-g** [comment]
There is no real need to update the documentation on the companion app here: if a recent VDH version is being run and proxy is used, then the add-on will request the update the coapp to 1.1.1 or later to go further.

I'm unsure about your question on other browsers. Currently VDH only runs on Firefox. It will soon be ported to Chrome, with the same coapp being used.

**Comment by methuzla** [comment]
Thanks.
I did think it would be _nice_ if the documentation _said_ that now the co-app will be using the ff proxy (_whereas before VDH wasn't, and was saying that was safe)_, just to save everyone's man-hours in going to check if it was so, visiting forums, asking questions and so on.,,

I look forward to seeing it working though. Thanks

**Comment by mi-g** [comment]
The "safe" mention was about the application not containing malware, which is a legitimate question users would ask when requested to install an application.

The proxy changes will be part of the changelog notice when 7.1.2 will be made public, along with a long list of other improvements.

**Comment by mi-g** [comment]
Cleaning up bug entries.
Current version of VDH is 7.2.2.

**Comment by lazybirddog** [comment]
(it's closed) But I have a similar question:
1. I plan to download a video in Firefox private mode using Browsec VPN
2. Then the extension said I have to use the coapp.exe, so I downloaded it
3. The 'coapp' needs an entry on my firewall to reach internet, I add it
4. Then my question is that:

The coapp (v 1.5.0) will use my ISP IP for the download directly,
or the coapp communicate 'only' via the browser extension (VDH), which will use my browser IP, which can be secured e.g. with Browsec VPN?

**Comment by mi-g** [comment]
If you use a browser-only VPN solution (this seems to be the case with Browsec VPN) the coapp will download from the ISP IP address. If you installed a computer-wide VPN solution, the coapp will use the VPNized IP.

**Comment by lazybirddog** [comment]
So basically it's a total dangerous mixture for a novice user. What if somebody skip the mentioned layer (computer-wide VPN) for only one video download? As I think, they are traceable easily be the site maintainer, am I right?

**Comment by mi-g** [comment]
Yes, when you play with VPNs and hiding your IP, you have to understand how it works and what are the limitations.
