### ISSUE TITLE
Why is vdhcoapp accessing installed firefox extensions?

### ISSUE THREAD

**Issue by Johann-Tree** [mi-g/vdhcoapp#19]
lsof -p <PID of net.downloadhelper.coapp> lists the XPI-files of installed firefox extensions. Why is vdhcoapp accessing them?

Using Ubuntu 16.04.3 with net.downloadhelper.coapp 1.1.1

**Comment by mi-g** [comment]
vdhcoapp does not access any XPI, but this is a native app and as such, its process is launched by Firefox which needs to open the XPI files.
