### ISSUE TITLE
Failed when building vpx

### ISSUE THREAD

**Issue by reallyrez** [mi-g/vdhcoapp#20]
I was trying to build vdhcoapp 1.3.1 and this was an error I found when I was executing build-apps.sh:

Building vpx
  enabling pic
  disabling examples
  disabling docs
  disabling install_bins
  disabling install_srcs
  disabling unit_tests
  enabling postproc
  enabling multi_res_encoding
  enabling vp9_temporal_denoising
  enabling vp9_postproc
  enabling vp8_encoder
  enabling vp8_decoder
  enabling vp9_encoder
  enabling vp9_decoder
Configuring for target 'x86_64-linux-gcc'
  enabling x86_64
  enabling runtime_cpu_detect
  enabling mmx
  enabling sse
  enabling sse2
  enabling sse3
  enabling ssse3
  enabling sse4_1
  enabling avx
  enabling avx2
  using nasm
Toolchain is unable to link executables

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.
[root@fedora converter]# 

Any idea how to solve this?

**Comment by mi-g** [comment]
Can you check the config.log file ? It may contain useful information about what tool is missing or not working

**Comment by reallyrez** [comment]
Uhh, where can I find this config.log?

All I got when I ran whereis was this:
[root@fedora reza]# whereis config.log
config: /usr/share/config.site /usr/share/man/man5/config.5ssl.gz

**Comment by mi-g** [comment]
My understanding was that you got the error compiling the vpx library. So this is where to start looking for.

**Comment by reallyrez** [comment]
Here is the config.log from my src-build:

# ./configure --prefix=/home/reza/vdhcoapp/converter/src-build/linux/64/deps --target=x86_64-linux-gcc --enable-pic --disable-examples --disable-docs --disable-install-bins --disable-install-srcs --disable-unit-tests --size-limit=16384x16384 --enable-postproc --enable-multi-res-encoding --enable-temporal-denoising --enable-vp9-temporal-denoising --enable-vp9-postproc
  enabling vp8_encoder
  enabling vp8_decoder
  enabling vp9_encoder
  enabling vp9_decoder
Configuring for target 'x86_64-linux-gcc'
  enabling x86_64
check_cpp
BEGIN /tmp/vpx-conf-19708-23091.c
     1	#if !defined(__ILP32__) || !defined(__x86_64__)
     2	#error "not x32"
     3	#endif
END /tmp/vpx-conf-19708-23091.c
gcc -E -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
/tmp/vpx-conf-19708-23091.c:2:2: error: #error "not x32"
 #error "not x32"
  ^~~~~
  enabling runtime_cpu_detect
check_cflags -mmmx
check_cc -Werror -mmmx
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -Werror -mmmx -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
  enabling mmx
check_cflags -msse
check_cc -Werror -msse
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -Werror -msse -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
  enabling sse
check_cflags -msse2
check_cc -Werror -msse2
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -Werror -msse2 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
  enabling sse2
check_cflags -msse3
check_cc -Werror -msse3
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -Werror -msse3 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
  enabling sse3
check_cflags -mssse3
check_cc -Werror -mssse3
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -Werror -mssse3 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
  enabling ssse3
check_cflags -msse4
check_cc -Werror -msse4
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -Werror -msse4 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
  enabling sse4_1
check_cflags -mavx
check_cc -Werror -mavx
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -Werror -mavx -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
  enabling avx
check_cflags -mavx2
check_cc -Werror -mavx2
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -Werror -mavx2 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
  enabling avx2
  using nasm
check_asm_align
BEGIN /tmp/vpx-conf-19708-23091.asm
     1	section .rodata
     2	align 16
END /tmp/vpx-conf-19708-23091.asm
nasm -Ox -f elf64 -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.asm
BEGIN /tmp/vpx-conf-19708-23091.x
     1	There are 5 section headers, starting at offset 0x40:
     2	
     3	Section Headers:
     4	  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
     5	  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
     6	  [ 1] .rodata           PROGBITS        0000000000000000 000180 000000 00   A  0   0 16
     7	  [ 2] .shstrtab         STRTAB          0000000000000000 000180 000023 00      0   0  1
     8	  [ 3] .symtab           SYMTAB          0000000000000000 0001b0 000048 18      4   3  8
     9	  [ 4] .strtab           STRTAB          0000000000000000 000200 00001f 00      0   0  1
    10	Key to Flags:
    11	  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
    12	  L (link order), O (extra OS processing required), G (group), T (TLS),
    13	  C (compressed), x (unknown), o (OS specific), E (exclude),
    14	  l (large), p (processor specific)
END /tmp/vpx-conf-19708-23091.x
check_cxxflags -DNDEBUG
check_cxx -Werror -DNDEBUG
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -Werror -DNDEBUG -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -DNDEBUG
check_cc -Werror -DNDEBUG
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -Werror -DNDEBUG -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -O3
check_cxx -Werror -O3
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -Werror -O3 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -O3
check_cc -Werror -O3
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -Werror -O3 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -fPIC
check_cxx -Werror -fPIC
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -Werror -fPIC -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -fPIC
check_cc -Werror -fPIC
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -Werror -fPIC -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
check_cxx -Werror -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -Werror -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
check_cc -Werror -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -Werror -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cc
BEGIN /tmp/vpx-conf-19708-23091.c
     1	unsigned int e = 'O'<<24 | '2'<<16 | 'B'<<8 | 'E';
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cc
BEGIN /tmp/vpx-conf-19708-23091.c
     1	static inline function() {}
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
/tmp/vpx-conf-19708-23091.c:1:15: warning: return type defaults to ‘int’ [-Wimplicit-int]
 static inline function() {}
               ^~~~~~~~
check_header pthread.h
check_cpp
BEGIN /tmp/vpx-conf-19708-23091.c
     1	#include "pthread.h"
     2	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -E -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wall
check_cxx -Werror -Wall
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wall -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wall
check_cc -Werror -Wall
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wall -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wdeclaration-after-statement
check_cxx -Werror -Wdeclaration-after-statement
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wdeclaration-after-statement -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wdeclaration-after-statement
check_cc -Werror -Wdeclaration-after-statement
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Werror -Wdeclaration-after-statement -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wdisabled-optimization
check_cxx -Werror -Wdisabled-optimization
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wdisabled-optimization -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wdisabled-optimization
check_cc -Werror -Wdisabled-optimization
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Werror -Wdisabled-optimization -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wfloat-conversion
check_cxx -Werror -Wfloat-conversion
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wfloat-conversion -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wfloat-conversion
check_cc -Werror -Wfloat-conversion
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Werror -Wfloat-conversion -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wpointer-arith
check_cxx -Werror -Wpointer-arith
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wpointer-arith -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wpointer-arith
check_cc -Werror -Wpointer-arith
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Werror -Wpointer-arith -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wtype-limits
check_cxx -Werror -Wtype-limits
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wtype-limits -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wtype-limits
check_cc -Werror -Wtype-limits
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Werror -Wtype-limits -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wcast-qual
check_cxx -Werror -Wcast-qual
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wcast-qual -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wcast-qual
check_cc -Werror -Wcast-qual
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Werror -Wcast-qual -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wvla
check_cxx -Werror -Wvla
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wvla -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wvla
check_cc -Werror -Wvla
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Werror -Wvla -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wimplicit-function-declaration
check_cxx -Werror -Wimplicit-function-declaration
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wimplicit-function-declaration -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wimplicit-function-declaration
check_cc -Werror -Wimplicit-function-declaration
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Werror -Wimplicit-function-declaration -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wuninitialized
check_cxx -Werror -Wuninitialized
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wuninitialized
check_cc -Werror -Wuninitialized
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Werror -Wuninitialized -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wunused
check_cxx -Werror -Wunused
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wunused -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wunused
check_cc -Werror -Wunused
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wuninitialized -Werror -Wunused -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cxxflags -Wextra
check_cxx -Werror -Wextra
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int x;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wextra -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cflags -Wextra
check_cc -Werror -Wextra
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wuninitialized -Wunused -Werror -Wextra -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cflags -Wundef
check_cc -Werror -Wundef
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wuninitialized -Wunused -Wextra -Werror -Wundef -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_cflags -Wshorten-64-to-32
check_cc -Werror -Wshorten-64-to-32
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wuninitialized -Wunused -Wextra -Wundef -Werror -Wshorten-64-to-32 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
gcc: error: unrecognized command line option ‘-Wshorten-64-to-32’
check_cxx
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int z;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cxx
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int z;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_cxx
BEGIN /tmp/vpx-conf-19708-23091.cc
     1	int z;
END /tmp/vpx-conf-19708-23091.cc
g++ -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.cc
./build/make/configure.sh: line 292: g++: command not found
check_header stdio.h
check_cpp
BEGIN /tmp/vpx-conf-19708-23091.c
     1	#include "stdio.h"
     2	int x;
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wuninitialized -Wunused -Wextra -Wundef -E -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
check_ld
check_cc
BEGIN /tmp/vpx-conf-19708-23091.c
     1	int main(void) {return 0;}
END /tmp/vpx-conf-19708-23091.c
gcc -m64 -DNDEBUG -O3 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wuninitialized -Wunused -Wextra -Wundef -c -o /tmp/vpx-conf-19708-23091.o /tmp/vpx-conf-19708-23091.c
ld -m64 -o /tmp/vpx-conf-19708-23091.x /tmp/vpx-conf-19708-23091.o -lpthread
ld: unrecognised emulation mode: 64
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe

**Comment by mi-g** [comment]
It shows `g++: command not found` so you are probably missing some compiling tools. Maybe the `gcc-c++` package ?

**Comment by reallyrez** [comment]
yep, thanks for your response. By now I already installed gcc-c++ (I'm on fedora), but I encountered a new error, maybe you could help me? From console I got this:

vpx_dsp/x86/intrapred_sse2.asm:64: error: invalid combination of opcode and operands
third_party/x86inc/x86inc.asm:1383: ... from macro `movd' defined here
third_party/x86inc/x86inc.asm:1283: ... from macro `RUN_AVX_INSTR' defined here
make[1]: *** [Makefile:181: vpx_dsp/x86/intrapred_sse2.asm.o] Error 1
make: *** [Makefile:17: .DEFAULT] Error 2
[root@fedora vdhcoapp]#

**Comment by reallyrez** [comment]
Here's another 
[config.log](https://github.com/mi-g/vdhcoapp/files/1692773/config.log)

**Comment by mi-g** [comment]
You should search google for `vpx_dsp/x86/intrapred_sse2.asm:64: error: invalid combination of opcode and operands` and see where it takes you. I don't think i can help much more here.

**Comment by mi-g** [comment]
Cleaning up bug entries.
Latest release has vpx updates anyway.
