### ISSUE TITLE
n2.9.13 doesn't exist as a tag for ffmpeg

### ISSUE THREAD

**Issue by hvindin** [mi-g/vdhcoapp#21]
The tag in the script to pull the relevant versions of the dpeendencies declares the ffmpeg version as n2.91.3

However in the ffmpeg the tag 2.9..13 doesn't exist. Did you mistype an indended branch?

As a side note, it seems like it would speed up the git clone operations a little if you ran with the syntax of

```bash
git clone "${SRCIDR}" --branch="${WHATVR_VER}" --single-branch
```

which would work for all but the vorbis git repo because you are pointing directly at a commit hash.

**Comment by mi-g** [comment]
Latest [vdhcoapp 1.2.1](https://github.com/mi-g/vdhcoapp/releases/tag/v1.2.1) is based on ffmpeg n4.0.
