### ISSUE TITLE
A request please.

### ISSUE THREAD

**Issue by DanaMW** [mi-g/vdhcoapp#22]
Very nice  work.  Haven't tried your downloader for a couple years but it is up at the top for web extensions, thank you.
My issue is in what handles the downloads. I put effort into not letting the browser handle downloads and was wondering if there is a method currently  for me to allow my download manager to take the downloads. If there is not that would be my request, for a third download processor option.  You can imagine how personal people take their setup and well i found other inferior scripts and add-on that allow that but I am hoping to  come to terms because I wont have any  problems  putting my money where my mouth is if I can work  that out. If you have suggestions or questions let me know, I am  looking forward to working it out, and thank you for listening.

**Comment by mi-g** [comment]
Sorry, that's not possible. It takes a very specific API between the "downloader" and VDH, so we cannot just replace the coapp downloader with another one.

**Comment by DanaMW** [comment]
Understood, thank you
