### ISSUE TITLE
idem with "net.downloadhelper.coapp-1.1.3.dmg" : zéro octet !!!

### ISSUE THREAD

**Issue by me59** [mi-g/vdhcoapp#26]
sorry I'm a béta user...

**Comment by mi-g** [comment]
Do you try to get the file from those links: [https://github.com/mi-g/vdhcoapp/releases/download/v1.1.3/net.downloadhelper.coapp-1.1.3.pkg](https://github.com/mi-g/vdhcoapp/releases/download/v1.1.3/net.downloadhelper.coapp-1.1.3.pkg) [https://github.com/mi-g/vdhcoapp/releases/download/v1.1.3/net.downloadhelper.coapp-1.1.3.dmg](https://github.com/mi-g/vdhcoapp/releases/download/v1.1.3/net.downloadhelper.coapp-1.1.3.dmg) ?

**Comment by me59** [comment]
Yes, zéro octet for both pkg and dmg!!!

2018-05-12 14:02 GMT+02:00 Michel Gutierrez <notifications@github.com>:

**Comment by mi-g** [comment]
I am sorry but there is nothing we can do on our side. Those files are available for HTTP download on github servers. You may have some kind of filter on your computer or home network, like aggressive firewall rules, but it's definitely not an issue of the vdhcoapp project.
