### ISSUE TITLE
Minor issue: Size of installation wrongly reported

### ISSUE THREAD

**Issue by sm8ps** [mi-g/vdhcoapp#29]
The Linux 64 bits deb package reports a humongous size of 97.3 GB (!) when opened with the Ubuntu 16.04 software center (see attachment; add-on version: 3.1.4 on Firefox 60). This looks a bit troubling at first glance. It installs and works fine, however. I cannot tell if the issue lies within the package or in the way it is handled by the software center.
Anyways, thanks for this very useful piece of software!
![auswahl_045](https://user-images.githubusercontent.com/3989424/40532634-632f62fc-6000-11e8-8552-c0a609f5a7e8.png)

**Comment by mi-g** [comment]
Yes, that's right. This has been fixed in vdhcoapp 1.2.1, to be released in the next 48 hours.

**Comment by mi-g** [comment]
[vdhcoapp release 1.2.1](https://github.com/mi-g/vdhcoapp/releases/tag/v1.2.1) is available and includes the fix.
