### ISSUE TITLE
When I convert a file, downloading it from youtube, I get this error

### ISSUE THREAD

**Issue by medioman** [mi-g/vdhcoapp#3]
Exit code: 127
/home/don/net.downloadhelper.coapp-1.0.9/converter/build/linux/64/ffprobe: error while loading shared libraries: libnuma.so.1: cannot open shared object file: No such file or directory

**Comment by medioman** [comment]
my distro is arch linux

**Comment by mi-g** [comment]
I must say, i have no idea.
1.0.9 is no different from other versions regarding the ffxxxx binaries.
Assuming Debian/Ubuntu Linux distribution, did you try installing `libnuma` (`sudo apt-get install libnumba1`) ?

**Comment by mi-g** [comment]
I don't know for sure on arch linux, but i guess there is an easy way to install `libnuma`.

**Comment by Akipe** [comment]
I had the same error on Archlinux: I solved it by installing the "numactl" dependency (who include libnuma).

**Comment by medioman** [comment]
Thank @Akipe,i solved!
Best regards
