### ISSUE TITLE
MacOS.Backdoor.Bella.A

### ISSUE THREAD

**Issue by TXC** [mi-g/vdhcoapp#35]
When installing the "PKG" version i got a warning for "MacOS.Backdoor.Bella.A".

Is the PKG tainted?

**Comment by mi-g** [comment]
False positives are common. You should report it to your anti-virus editor so the file will be verified manually and white-listed.

**Comment by Henrietta1989** [comment]
Can anybody who knows these virus things, prove that this installer is not dangerous? I don't dare to install it because of Bella. Thanks

**Comment by XX-J** [comment]
@Henrietta1989

 Is not dangerous: https://virusscan.jotti.org/en-US/filescanjob/0cjel9ydb4,x6ktdndzut,nxy8q96t7h,499drmgfr6,2bvv0ojtlt
