### ISSUE TITLE
cannot get veriification of coapp 

### ISSUE THREAD

**Issue by marc206** [mi-g/vdhcoapp#4]
Had the Firefox extension Video DownloadHelper running fine and it just stopped working. Did a remove and reinstall of both Download helper and Coapp but on each occasion it fails to verify the existence of the coapp. I even did a fresh install of Firefox and a flush of all residual files before reinstall.  The recheck button does nothing
<img width="977" alt="screen shot 2017-11-29 at 17 31 23" src="https://user-images.githubusercontent.com/34103980/33389626-722f4b6a-d52b-11e7-933b-ee756b6b3889.png">

And I have verified the files are in place
<img width="520" alt="screen shot 2017-11-29 at 17 31 52" src="https://user-images.githubusercontent.com/34103980/33389667-8c584690-d52b-11e7-962e-aab4a2b97691.png">

Any help please

**Comment by mi-g** [comment]
Did you install the CoApp with the .pkg or the .dmg ?

**Comment by marc206** [comment]
I have tried both options. The final install as per screenshot is by .dmg

**Comment by mi-g** [comment]
When using the .dmg, did you execute the required additional commands ?

**Comment by marc206** [comment]
If you refer to the forcing Mac OS to run the app, then yes i have forced it to run.  If there is something else then it is not clear.
<img width="590" alt="screen shot 2017-11-29 at 18 09 40" src="https://user-images.githubusercontent.com/34103980/33391329-8c4aca38-d530-11e7-8976-bab3acc6bf60.png">

**Comment by mi-g** [comment]
Can you check the content of the file `/Library/Application Support/Mozilla/NativeMessagingHosts/net.downloadhelper.coapp.json` or `~/Library/Application Support/Mozilla/NativeMessagingHosts/net.downloadhelper.coapp.json` ?
Referring to [this documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_manifests).

**Comment by marc206** [comment]
<img width="636" alt="screen shot 2017-11-29 at 18 36 24" src="https://user-images.githubusercontent.com/34103980/33392570-5eeda1ec-d534-11e7-921a-636282619e62.png">

{
    "name": "net.downloadhelper.coapp",
    "description": "Video DownloadHelper companion app",
    "path": "/Applications/net.downloadhelper.coapp.app/Contents/MacOS/bin/net.downloadhelper.coapp-mac-64",
    "type": "stdio",
    "allowed_extensions": [
        "weh-native-test@downloadhelper.net",
        "{b9db16a4-6edc-47ec-a1f4-b86292ed211d}"
    ]
}

**Comment by marc206** [comment]
Sry forgot to say i don't have file locations:-
/Library/Application Support/Mozilla/ManagedStorage/<name>.json
/Library/Application Support/Mozilla/PKCS11Modules/<name>.json

And i confirm i am running Mozilla version 57 on a fresh install today

**Comment by mi-g** [comment]
Ok, i can see that problem on Mac. I'm on it.

**Comment by mi-g** [comment]
I found and fixed the problem. Release 1.0.10 of the companion app is available directly from github in the [release page](https://github.com/mi-g/vdhcoapp/releases/tag/v1.0.10).
You may need to restart the add-on from the settings (More > Restart add-on) in order to reset a possible 1.0.9 version still running.
