### ISSUE TITLE
Companion app not working

### ISSUE THREAD

**Issue by PrimordialHelios** [mi-g/vdhcoapp#41]
Running Firefox 64 bit 63.0.1 on Fedora 28. I've installed the companion app from the downloads page into `/opt/net.downloadhelper.coapp` and run `sudo /opt/net.downloadhelper.coapp/bin/net.downloadhelper.coapp-linux-64 install`. I've restarted Firefox several times, but whenever I try to download a video, I get the message saying I need to install the companion app.

I'm wondering if this might be due to Fedora having a somewhat different filesystem layout compared to other distros. Would anybody be able to tell me where any log files or manifests might be located, so I can try and debug what's happening?

**Comment by mi-g** [comment]
If the coapp wouldn't work on Fedora, a lot of users would have complained about this so my guess is that your issue is specific to your environment.

Can you check [this document](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#Manifest_location) and verify that the coapp manifests are at the expected location ?

**Comment by webenhanced** [comment]
On Fedora 28, it works great installed with the --user option. That is how I run it. Had no issues for ages now. Of course, this is OK as I am the only user on the computer.

For a system wide install, I would want the app to install into /usr/local/bin on Fedora. Much easier with permissions and SELinux. Being in /opt/ it could have permissions, selinux, or PATH troubles.

**Comment by PrimordialHelios** [comment]
@mi-g both /usr/lib/mozilla/native-messaging-hosts/ and /usr/lib64/mozilla/native-messaging-hosts/ had the manifests installed. Using `--user` during install as @webenhanced suggested fixed it.

Thanks for the help!
