### ISSUE TITLE
.part files left behind when a manifest is removed mid-stream

### ISSUE THREAD

**Issue by rbtcollins** [mi-g/vdhcoapp#42]
This happens with some live broadcasts, and results in an unusable stream - it would be much nicer to properly close off the .part file when this happens.

**Comment by jkemp814** [comment]
I agree. I wish there was a way to auto-save the file every 5-10 minutes. At least then the files could be stitched together instead of a total lost. We lost our entire broadcast due to a cut in the feed. Now we manually start and stop so the files can be saved, but there is a gap in the stream.

**Comment by jkemp814** [comment]
I have found setting "Chunked manifests CoApp requests" to on, seems to help.

**Comment by jkemp814** [comment]
Can the ffmpeg in vdhcapp use the mkv container? in conjunction with the 'copy' codec? When I use my own locally installed ffmpeg directly, using those options, it works perfect.

ffmpeg -i hhtps://your_stream_here.m3u8 -c:v copy -c:a copy -loglevel error /save_to_here/out.mkv

There is hardly any CPU usage this way. If the stream is cut the mkv container does a much better job handling the manifest

**Comment by mi-g** [comment]
.part cleanup is the extension responsibility not the coapp which only provides low level tools.
