### ISSUE TITLE
can't get it to work on OSX

### ISSUE THREAD

**Issue by clankill3r** [mi-g/vdhcoapp#43]
I keep getting

```
Companion application upgrade required
You are running the companion application version 1.0.10 but this feature requires version 1.2.1
```
Then when I update it says it is ready to use, and then I get the same error from above again.
Rebooting does not help.

OSX 10.12.6

**Comment by mi-g** [comment]
Try removing the manifest files in `~/Library/.../net.downloadhelper.coapp.json` before reinstalling.
