### ISSUE TITLE
YT, issue

### ISSUE THREAD

**Issue by parshy** [mi-g/vdhcoapp#46]
Won't work for YouTube rentals or purchases. I was willing to pay for discs, but the discs I keep receiving (not BD), believe it or not, are formatted to an aspect ratio that isn't the original one (4:3). So I can buy or rent on YouTube, but I want the freedom to play the file wherever I wish, which requires apps like this, but it won't work. Only the first eight seconds play and then video pixelates and sound disappears. The movies play fine in my browser on the site, so the data is being transmitted to my browser. You just need to figure out how to get that data from screen to file.

**Comment by Bumbadawg** [comment]
The scripts to decipher the data are minified and might be randomized.
One way to achieve the re-ordered data dumping would be to monitor the order, and dump the data with the companion app.
On the political side, Google would try to take down this addon if it counters their paywall restrictions. Mozilla would oblige since it's a partner and an american-based service.

**Comment by parshy** [comment]
> One way to achieve the re-ordered data dumping would be to monitor the order, and dump the data with the companion app.

How might one go about this, were one to need this on the rare occasion?

**Comment by Bumbadawg** [comment]
Actually nevermind, it was in the case file parts were not encrypted, but since they are, it's useless.

**Comment by parshy** [comment]
> Actually nevermind, it was in the case file parts were not encrypted, but since they are, it's useless.

K, thanks anyway.

**Comment by mi-g** [comment]
Since the beginning of the VDH project, we've made sure to avoid features that could get us into troubles (like decrypting media intentionally protected). This is why VDH has been around for 13 years.
Closing the bug as this is not a coapp issue anyway.
