### ISSUE TITLE
Failed aggregating : libmvec.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sebma** [mi-g/vdhcoapp#53]
Hi,

I get this error on Ubuntu : 
```bash
Failed aggregating "Praise | Joseph Prince | March 23, 2020 - Praise - Watch TBN - Trinity Broadcasting Network"
/opt/net.downloadhelper.coapp/converter/build/linux/64/ffmpeg: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory
```

Any clue ?

**Comment by sebma** [comment]
Workaround in the meantime if you have a system ffmpeg already installed and working : https://github.com/mi-g/vdhcoapp/issues/49#issuecomment-605642030

**Comment by sebma** [comment]
Workaround in the meantime if you already have a system ffmpeg installed and working :)  : https://github.com/mi-g/vdhcoapp/issues/49#issuecomment-605642030

**Comment by mi-g** [comment]
Please re-open if you still get the problem with latest 1.6.0 release
