### ISSUE TITLE
Can not DL v1.4.0

### ISSUE THREAD

**Issue by bjd-s** [mi-g/vdhcoapp#54]
I can't DL v1.4.0, when i tried to click on button here i had nothing :
https://www.downloadhelper.net/install-coapp?browser=firefox

Same on this URL :
https://github.com/mi-g/vdhcoapp/releases/download/v1.4.0/VdhCoAppSetup-1.4.0.exe

**Comment by mi-g** [comment]
Maybe a firewall issue ?
Did you try downloading a .exe file from another project, like https://github.com/hasherezade/dll_to_exe/releases/download/v1.1/dll_to_exe.exe (i picked this file randomly)

**Comment by bjd-s** [comment]
Was a firewall yep, sorry for the post ! :)
