### ISSUE TITLE
Please support systems with glibc < 2.27

### ISSUE THREAD

**Issue by tari3x** [mi-g/vdhcoapp#55]
The companion app currently fails on OpenSuSE 15.1 because the system only has glibc 2.26. Trying to build the companion app from source does not work since it is not accepted by the extension (is that expected, or am I doing something wrong here?)

Is there any way to get this running without upgrading the whole system? 

This has been discussed here before, but without conclusion: 
https://groups.google.com/forum/#!topic/video-downloadhelper-q-and-a/Z3iY4yhFvU8

**Comment by tari3x** [comment]
I tried replacing ffmpeg, ffprobe, and ffplay in converter/ by system versions. The error about missing glibc 2.27 disappeared, but I am now running into other issues, and I'm not sure if those are related.

**Comment by tari3x** [comment]
The other error is resolved, so this method works.

**Comment by raph82** [comment]
Lighter alternative than to support older glibc: add a dependency to the glibc building version on the package. Then the new CoApp version can not be installed on older systems. These would keep working with the last CoApp supported version.

Better for the user than updating the CoApp, getting errors, looking for answers, posting to the forum, getting angry about it... ;)

By the way, for context, some popular distro like Ubuntu (and derived distros) are still supporting LTS releases with glibc 2.23 until 2021 (see Ubuntu LTS 16.04 for example).

**Comment by axelandy** [comment]
> Lighter alternative than to support older glibc: add a dependency to the glibc building version on the package. Then the new CoApp version can not be installed on older systems. These would keep working with the last CoApp supported version.
> 
> Better for the user than updating the CoApp, getting errors, looking for answers, posting to the forum, getting angry about it... ;)
> 
I too was in this boat.  It would have been nice if VDH didn't prompt me to upgrade the coapp when my system doesn't support the newer version, or to be warned by a dependency when trying to install.

**Comment by mi-g** [comment]
The latest release 1.6.0 includes `.tar.gz` and `.deb` packages for both Linux 64 and 32 bits: https://github.com/mi-g/vdhcoapp/releases/tag/v1.6.0

**Comment by raph82** [comment]
Thank you!
