### ISSUE TITLE
Please provide more informaiton about what the installer is doing

### ISSUE THREAD

**Issue by tari3x** [mi-g/vdhcoapp#56]
Would it be easy to change the installer to tell me what files it is installing and to what locations please? This would be very useful for debugging why things don't work.

**Comment by mi-g** [comment]
I assume you are talking about Windows.
The installation is very standard and installs the coapp in the `Program Files` folder plus a few things in the registry for the browsers to find the coapp.
Most users won't care much about this and could be confused by those details. For those who care like yourself, you can check the ISS file that is used to create the installer: https://github.com/mi-g/vdhcoapp/blob/master/assets/app.iss.ejs

**Comment by tari3x** [comment]
I'm talking about linux.

I wouldn't care much about this if the tool just worked out of the box. Unfortunately it doesn't - it took me 2-3 hours of hackery to get it right (see the other issues I opened). Any help with that is always appreciated.

**Comment by mi-g** [comment]
On Linux this is even simpler: you can run `dpkg -X net.downloadhelper.coapp.XXX.deb` or `tar tvf net.downloadhelper.coapp.XXX.tar.gz` to see the content of the packages.

**Comment by tari3x** [comment]
I'm confused. I'm talking about this command:
/usr/local/net.downloadhelper.coapp-1.6.0/bin/net.downloadhelper.coapp-linux-64 install
What does it do?

**Comment by mi-g** [comment]
It creates manifest files at various locations for the browsers (currently Firefox, Chrome and Edge) to find the companion app.
The documentation about those manifest files can be found at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests

**Comment by tari3x** [comment]
Well, I guess my request is that it should print the files that it is creating. It could do it with a -verbose flag so people who don't want to see it don't get confused.

**Comment by tari3x** [comment]
Is this resolved? I still don't see any output when running the install command.

**Comment by posita** [comment]
This needs to be reopened. `.../bin/net.downloadhelper.coapp-linux-64 install ...` and `.../bin/net.downloadhelper.coapp-linux-64 uninstall ...` are entirely opaque to the user. `uninstall` isn't even documented. There's no `help` or `--help` option. The user is expected to blindly run these from the [installation instructions](https://www.downloadhelper.net/install-coapp#extra-targz64) and can't discover--even after-the-fact--what effect running those commands had. Not providing transparency works against the assertions made in the [FAQ](https://www.downloadhelper.net/install-coapp#how-safe).

**Comment by paulrouget** [comment]
> This needs to be reopened. `.../bin/net.downloadhelper.coapp-linux-64 install ...` and `.../bin/net.downloadhelper.coapp-linux-64 uninstall ...` are entirely opaque to the user. `uninstall` isn't even documented. There's no `help` or `--help` option. The user is expected to blindly run these from the [installation instructions](https://www.downloadhelper.net/install-coapp#extra-targz64) and can't discover--even after-the-fact--what effect running those commands has or had. Not providing transparency works against the assertions made in the [FAQ](https://www.downloadhelper.net/install-coapp#how-safe).

The latest builds do report what filed are created where. We are working on a better version of the coapp trying to address as much request as possible. You can see the work in master, but it hasn't been released yet. It's still work in progress.

**Comment by tari3x** [comment]
Would it be possible to reopen the issue until it is addressed?

**Comment by paulrouget** [comment]
> Would it be possible to reopen the issue until it is addressed?

I've filed a specific issue: https://github.com/aclap-dev/vdhcoapp/issues/163 - this will be part of the version 2 of the coapp.
