### ISSUE TITLE
please provide more information in the browser when "Verifying Companion App… "

### ISSUE THREAD

**Issue by tari3x** [mi-g/vdhcoapp#57]
Currently "Verifying Companion App…" is quiet about why it is failing. Could it please tell me where it is looking for the companion app, and whether it failed because the app has not been found, or because it has been found or is incompatible, or whatever other reason?

**Comment by tari3x** [comment]
More specifically, I get no error message when having installed companion app from source. It just says "verifying companion app...".

**Comment by sjau** [comment]
I'm facing the same problem having tried to package it for NixOS. Nixos does break with traditional linux FHS and uses '/nix/store/{sha256}-packagename-version/....'.

It would be great if in the browser extension one could select where the companion app is or where it's trying to look for.

**Comment by jbshirk** [comment]
This is the only issue referencing NixOS. Hoping one day instructions will turn up.

**Comment by mi-g** [comment]
I agree that getting more clues when the browser does not find the companion app would be very helpful, but unfortunately, we display all the information we get from the browser.

**Comment by hatch01** [comment]
> I'm facing the same problem having tried to package it for NixOS. Nixos does break with traditional linux FHS and uses `/nix/store/{sha256}-packagename-version/....`.
> 
> It would be great if in the browser extension one could select where the companion app is or where it's trying to look for.

Do you still have your try to package it?
I would like to try myself.

**Comment by paulrouget** [comment]
Maybe it's easier with the most recent coapp (version 2) as the installs process has changed.

The important bit is to run `vdhcoapp install` command after installation, as a user.

**Comment by sjau** [comment]
> > I'm facing the same problem having tried to package it for NixOS. Nixos does break with traditional linux FHS and uses `/nix/store/{sha256}-packagename-version/....`.
> > It would be great if in the browser extension one could select where the companion app is or where it's trying to look for.
> 
> Do you still have your try to package it? I would like to try myself.

Don't have it anymore as I couldn't get it to work.
