### ISSUE TITLE
missing index.js file

### ISSUE THREAD

**Issue by bollow** [mi-g/vdhcoapp#59]
The file index.js (cf. https://github.com/mi-g/vdhcoapp/blob/master/index.js ) is missing in https://github.com/mi-g/vdhcoapp/releases/download/v1.5.0/net.downloadhelper.coapp-1.5.0-src.tar.gz

**Comment by mi-g** [comment]
You are correct, the file is missing. I fixed the issue in the master branch. Releases > 1.6.0 will have the `index.js` file in the source tarball.
