### ISSUE TITLE
Uninstall on Mac

### ISSUE THREAD

**Issue by adriangrantdotorg** [mi-g/vdhcoapp#6]
How do you uninstall this software on Mac OS Sierra?

**Comment by mi-g** [comment]
I guess you do that the "normal" way, by dragging the app icon to the trash icon.

**Comment by adriangrantdotorg** [comment]
But that's the issue. After installing the pkg file, I didn't see any app get installed. There's no new app called "Companion" or "Video Download Helper" hence the confusion as to how to install whatever was installed when I double-clicked the package. 

Would appreciate any and all help. Thanks

**Comment by mi-g** [comment]
This should be an application called "net.downloadhelper.coapp" in the /Applications folder.

**Comment by adriangrantdotorg** [comment]
Found it, thank you!
