### ISSUE TITLE
System wide install places firefox config in wrong folder

### ISSUE THREAD

**Issue by hhyyrylainen** [mi-g/vdhcoapp#7]
On Fedora 26 (64 bit) I have to run this command after doing a system wide install (`sudo /usr/local/net.downloadhelper.coapp-1.1.0/bin/net.downloadhelper.coapp-linux-64 install --system`) to get firefox to detect the companion app:

```
sudo cp /usr/lib/mozilla/native-messaging-hosts/net.downloadhelper.coapp.json  /usr/lib64/mozilla/native-messaging-hosts/
```

The file `net.downloadhelper.coapp.json` doesn't get detected if it is in the folder that the install script puts it in (`/usr/lib/mozilla/native-messaging-hosts/`). Instead it needs to be in `/usr/lib64/mozilla/native-messaging-hosts/`.

Not sure if this is caused by other native apps that I already had in `/usr/lib64/mozilla/native-messaging-hosts`. But at least some time ago when making my own firefox addon I too had to place it in that folder for it to work.

**Comment by mi-g** [comment]
Thanks for the feedback. I'll make sure this is fixed in the next coapp release.

**Comment by jamerlan** [comment]
@hhyyrylainen Thanks! I was re-installing this app many times.. and it still said: app is not installed/not found. Your solution helped me! 
BTW, there was no folder: /usr/lib64/mozilla/native-messaging-hosts/
I created it and then it works! 
P.S. Fedora 27

**Comment by mi-g** [comment]
[vdhcoapp 1.2.1](https://github.com/mi-g/vdhcoapp/releases/tag/v1.2.1) installs the manifest in `/usr/lib64/mozilla/native-messaging-hosts` if directory `/usr/lib64` exists on the system.
