### ISSUE TITLE
What does this app download automatically in the background?

### ISSUE THREAD

**Issue by sparkie3** [mi-g/vdhcoapp#74]
/opt/net.downloadhelper.coapp/bin/net.downloadhelper.coapp-linux-64 
This application is downloading in the background. What, exactly is it doing, as I have not given it any commands?

**Comment by sparkie3** [comment]
Just wanted to update this. I have a pretty slow connection, so I noticed it using the bandwidth. Around 200kb/sec. Seems that I was on reddit, and it had something to do with their media autoloading. It closes when I close that page. Has a toggle switch of some sort from the browser been considered to prevent this kind of behavior?

**Comment by r3nk0o** [comment]
Bump.

I noticed permanent up- and downstream traffic from the idling companion application, too.
What is it receiving? And somewhat more concerning, imho - why and what is it sending..?
Would appreciate some insight!

**Comment by mi-g** [comment]
For the records, if you want to monitor the traffic between the extension and the companion app, you can use the  [Weh Inspector extension](https://addons.mozilla.org/en-US/firefox/addon/weh-inspector/).
