### ISSUE TITLE
Not working on Chromium (Microsoft Edge)

### ISSUE THREAD

**Issue by Bryceed** [mi-g/vdhcoapp#76]
**I'm trying use the extension to get videos from HLS transmission, but even having this companion app installed and reopened the browser, this still asking to install the app when I try to download.**

> Companion app isn't installed: Access to the specified native messaging host is forbidden.

[VDH 7.3.9.0 - Chrome Web Store]
> **Browser:** Microsoft Edge (v83.0.478.44, stable 64-bits)
**OS:** Windows 10 Home (release 1909, build 18363.863) 
**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 Edg/83.0.478.44

![image](https://user-images.githubusercontent.com/42657376/83671699-85bd7c80-a5ab-11ea-8589-66902138cda8.png)

_*Button to "Verify again" changes nothing_

**Comment by adamwinn** [comment]
I'm seeing this too on Edge

**Comment by LAS786** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging?tabs=windows

**Comment by mi-g** [comment]
The latest versions of the extension (>= 7.3.8) and the coapp (>=1.6.0) support Edge (Chromium based)

**Comment by adamwinn** [comment]
It's not working for me using the above versions

![Screen Shot 2020-12-15 at 3 05 51 AM](https://user-images.githubusercontent.com/3028964/102200862-9ae06580-3e82-11eb-9c5d-9db793d26d78.jpg)

**Comment by mi-g** [comment]
It looks like you are running the Chrome version instead of the Edge version: https://microsoftedge.microsoft.com/addons/detail/video-downloadhelper/jmkaglaafmhbcpleggkmaliipiilhldn

**Comment by adamwinn** [comment]
Sorry about that!  It's working now!
