### ISSUE TITLE
Failed downloads lose the url

### ISSUE THREAD

**Issue by hhyyrylainen** [mi-g/vdhcoapp#8]
If I use firefox native download method whenever there is a fail the name of the download is stored in the download history, but when using this coapp this is the only error I get for failed downloads in downloadhelper errors tab:

```
Download error

Response code 403 (Forbidden)
```

Which is very unhelpful in determining which file failed to download. I'm using version 7.1.0. Sorry if I should have reported this as a downloadhelper bug instead.

**Comment by mi-g** [comment]
Ok, this is more something to be improved in the add-on itself regarding the way errors are reported rather than in the coapp. This has been noted in the VDH add-on bug list. Thanks.
