### ISSUE TITLE
Support older 32-bit Windows versions?

### ISSUE THREAD

**Issue by casper** [mi-g/vdhcoapp#81]
I'm trying to get this to work on Windows Vista 32-bit. 

The current binary installs fine, but when I run it I get these errors:

![image](https://user-images.githubusercontent.com/25386/94329113-ab3e1e00-ffc0-11ea-9ee5-01bc6e9de46f.png)

![image](https://user-images.githubusercontent.com/25386/94329115-aed1a500-ffc0-11ea-8580-e88dadae26eb.png)

Is there any way to get this to work on Vista, or maybe I could compile it with MSYS or MinGW on Vista for myself somehow?

**Comment by mi-g** [comment]
I would have thought this version (win-32) worked on Vista.
If you want to recompile the app to match your environment, you are very welcome but i won't be able to help much as i am not a Windows expert and the Vista+32bits combination is becoming obsolete on both hardware and software.

I'm closing the bug as we are not going to fix this particular case. Feel free to reopen if needed.
