### ISSUE TITLE
What should I do in this situation?

### ISSUE THREAD

**Issue by TheLittleBoy** [mi-g/vdhcoapp#94]
![094814](https://user-images.githubusercontent.com/3365421/121980629-d969c500-cdbe-11eb-913b-cb3ee64938e5.png)

**Comment by TheLittleBoy** [comment]
This is url : [http://tv.cctv.com/2019/02/12/VIDEwPu15nqJmdzKo19YRYw6190212.shtml](url)

**Comment by mi-g** [comment]
Sorry, this is definitely not a vdhcoapp issue.
